MvcApplication1/MvcApplication1/MvcApplication1/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class ListController : Controller
    {
        //
        // GET: /List/
        private forecastflowEntities1 _db = new forecastflowEntities1();

        public ActionResult Index(int pageid)
        {
            //return View(_db.data);
            //int Pageid = 1;
            int flag = pageid;
            int cloht_id = MyClass.myclothcount;
            jisuan(flag);
            if(pageid==1)
            {
                ViewBag.m = "右臂";
            }
            else if (pageid == 2)
            {
                ViewBag.m = "前胸";
            }else if (pageid == 3)
            {
                ViewBag.m = "后背";
            }
            else if (pageid == 4)
            {
                ViewBag.m = "左臂";
            }
            
            
            // return View(_db.data.Where(t => t.flag == flag));

            Indexdata ind = new Indexdata(flag);
            return View(ind);
        }
        //public ActionResult Index()
        //{
        //    return View(_db.data);
        //}


        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Add([Bind(Exclude = "Id")] MvcApplication1.Models.data data)
        {
            data.clothid = MyClass.myclothcount;
            _db.AddTodata(data);

            _db.SaveChanges();

            return new JsonResult() { Data = true };

        }
       
        public ActionResult forcast(int pageid,double cair)
        {
            var a = 1;
            return RedirectToAction("Index", new { pageid = pageid });
        }

        public ActionResult Delete(int id,int pageid)
        {
            var rec = _db.data.SingleOrDefault(t => t.id == id);

            _db.data.DeleteObject(rec);
            _db.SaveChanges();

            //actually, you hvae deleted the record
            //if you want to redirect to a url, you need use redirect funciton

            //return Redirect("List?pageid="+id);
            return RedirectToAction("Index", new { pageid = pageid });
            //return RedirectToAction("List?pageid="+id);
            // return new JsonResult() { Data = true };
        }

        public void jisuan(int flag)
        {
            double pingjun_in = 0;
            double pingjun_out = 0;
            double pingjun_flow = 0;
            double cair=0;
            double vent = 0;
            int count = 0;
            double flowhe = 0;
            var rec = _db.data.Where(t => t.flag == flag  && t.clothid==MyClass.myclothcount);
            foreach (var item in rec)
            {
                count++;
                if (item.flow == 0)
                {
                    item.flow = 1;
                }
                pingjun_in += (double)(item.fin) * (double)(item.flow);
                pingjun_out += (double)(item.fout) * (double)(item.flow);
                flowhe += (double)(item.flow);
            }

            if (flowhe == 0 || count == 0)
            {
                flowhe = 1;
                count = 1;
                pingjun_flow = 0;
            }
            else
            {
       
                pingjun_flow = flowhe / count;
            }

            pingjun_in = pingjun_in / flowhe;
            pingjun_out = pingjun_out / flowhe;

           // pingjun_flow = flowhe / count;
            //if (pingjun_out == 0)
            //{
            //    pingjun_out = 1;
            //}
            if ((pingjun_out - cair) == 0)
            {
                vent = 0;
            }
            else
            {
                vent = ((pingjun_in - pingjun_out) / (pingjun_out - cair)) * pingjun_flow;
            }
            //if (pingjun_out == 1)
            //{
            //    pingjun_out = 0;
            //}
            //if (pingjun_flow == 1)
            //{
            //    pingjun_flow = 0;
            //}

            var rec1 = _db.ave.SingleOrDefault(t => t.flag == flag);
            if (rec1 != null)
            {
                _db.ave.DeleteObject(rec1);
            }
            _db.SaveChanges();
            int a = MyClass.myclothcount;
            MvcApplication1.Models.ave avr = new MvcApplication1.Models.ave
            {
                cin = (decimal)pingjun_in,
                cout = (decimal)pingjun_out,
                cflow = (decimal)pingjun_flow,
                flag = flag,
                name = _db.dic.Single(t => t.flag == flag).name,
                tongfeng=(decimal)vent,
                clothid=MyClass.myclothcount
            };

            MvcApplication1.Models.ave average = new MvcApplication1.Models.ave();
            MvcApplication1.Models.Myave average1 = new MvcApplication1.Models.Myave();

            _db.AddToave(avr);
            _db.SaveChanges();

            //average.cflow = pingjun_flow;
            //average.cin = pingjun_in;
            //average.cout = pingjun_out;
            average.flag = flag;

            _db.SaveChanges();

        }

    }
}

MvcApplication1/MvcApplication1/MvcApplication1/Views/List/Add.cshtml
@model MvcApplication1.Models.data
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_AjaxLayout.cshtml";
}
<form class="form-horizontal" method="post" action="/List/Add">
<div class="control-group">
    <label class="control-label" for="inputEmail">@Html.LabelFor(m => m.fin)</label>
    <div class="controls">
        @Html.TextBoxFor(m => m.fin)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputPassword">@Html.LabelFor(m => m.fout)</label>
    <div class="controls">
        @Html.TextBoxFor(m => m.fout)
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="inputPassword">@Html.LabelFor(m => m.flow)</label>
    <div class="controls bindTdCloseIcon">
        @Html.TextBoxFor(m => m.flow)
    </div>
</div>
<input type="hidden" name="flag" id="flag" value="@Request.QueryString["pageid"]" />
</form>

MvcApplication1/MvcApplication1/MvcApplication1/Views/List/Index.cshtml
@model MvcApplication1.Models.Indexdata


<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/AddUser.js")"></script>
 <script language="javascript">
      function showTable(id) {
          var tb = document.getElementById(id);
          var rows = tb.rows;
          var oflow = new Number;
          var iflow = new Number;
          var pflow = new Number;
          pflow = 0;
          oflow = 0;
          iflow = 0;
          for (var i = 1; i < rows.length; i++) {
              var cells = rows[i].cells;
              oflow += cells[1].childNodes[0].value * cells[3].childNodes[0].value;
              iflow += cells[2].childNodes[0].value * cells[3].childNodes[0].value;
              pflow += cells[3].childNodes[0].value * 1;


              myform.outpingju.value = oflow / pflow;
              myform.inpingju.value = iflow / pflow;
              myform.flowpingju.value = pflow / (rows.length - 1);
          }

      }
      function showTd(id) {
          var td = document.getElementById(id);
          var cell = td.parentElement;
          alert(cell.childNodes[0].value);
          alert(cell.cellIndex);
      }

      function gotoForcast(linkObj) {
          $(linkObj).attr('href', "/List/forcast?cair=" + $('#cair').val()+"&pageid=" + @Request.QueryString["pageid"]);
      }
 </script>  
@*  <table   id="dataTable" class="table table-striped table-bordered table-hover table-condensed">
  <th>Cair：周围环境中示踪气体浓度(%)
  </th>
    <th>局部通风值<br>
    (L/min)</th>
  <tr  class="warning">
    <td><input type="text" name="cair" id="cair" value="@ViewBag.mess"><br/><a href="#" onclick="gotoForcast(this)" role="button" class="btn  btn-primary " >预测通风值</a>
    </td>
   <td>
   <input type="text" name="outpingju" id="nn" value=0 />  
   </td>
   </tr> 
  </table>
 @*<button class="btn btn-info" id="btnAddUser">平均值</button>*@
 <h1>@ViewBag.m</h1>
 <form name="myform">  
 <table   id="dataTable" class="table table-striped table-bordered table-hover table-condensed">
 @foreach (var item in Model.ave )
 {
   <th>Cout：衣下空间示踪气体浓度平均值(%)
   </th>
   <th>Cin：输入到衣下空间示踪气体浓度平均值(%)
   </th>
   <th>Flowrate：局部系统循环流量平均值(L/min)
     </th>
    <tr  class="warning">
    <td>
   <input type="text" name="outpingju" id="nn" value= @Html.DisplayFor(modelItem => item.cout) />  
   </td>
   <td>
   <input type="text" name="inpingju" id="nn"   value= @Html.DisplayFor(modelItem => item.cin) /> 
    </td>
   <td>
   <input type="text" name="flowpingju" id="nn"   value= @Html.DisplayFor(modelItem => item.cflow) /> 
    </td>
   </tr> 
 }
 </table>
  </form> 
<p>

@* <li>@Html.ActionLink("右臂通风计算", "add", "List", new { pageid = 1 }, null)</li>*@


<table   id="dataTable" class="table table-striped table-bordered table-hover table-condensed">
    <tr>
        <th>

        </th>
        <th>
            Cout(i)：衣下空间示踪气体浓度<br>(%)
        </th>
        <th>
            Cin(i)：输入到衣下空间示踪气体浓度<br>(%)
        </th>
        <th>
            Flowrate(i)：局部系统循环流量<br>(L/min)
        </th>
        <th>
        </th>
    </tr>
@{var count=0;
foreach (var item in Model.data)
{
    count++;
    var val = "第" + count + "组数据";
    <tr class="success">
        <td>
           <input type="text" name="out0" value="@val" />
        </td>
        <td>
           <input type="text" name="out0" value= @Html.DisplayFor(modelItem => item.fout) />
        </td>
        <td>
         <input type="text" name="out0" value= @Html.DisplayFor(modelItem => item.fin) />        
        </td>
        <td>
        <input type="text" name="out0" value=    @Html.DisplayFor(modelItem => item.flow) />     
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.id, pageid = Request.QueryString["pageid"] })
        </td>
    </tr>
}
}
</table>
<a href="/List/add?pageid=@Request.QueryString["pageid"]" role="button" class="btn  btn-info" data-target="#myModal" data-toggle="modal">添加数据</a>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><img src="@Url.Content("~/Images/logo.gif")" />添加数据</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
        <button class="btn" id="btnClose" data-dismiss="modal" aria-hidden="true">关闭</button>
        <button class="btn btn-primary" id="btnAddUser">保存</button>
    </div>
</div>